### ISSUE TITLE
Why is the file extension `.es6` and not `.js`

### ISSUE THREAD

**Issue by globexdesigns** [rambler-digital-solutions/es6-class-mixin#1]
This is a pretty bizarre choice and doesn't work with most processors which assume a `js` or `jsx` file extension.

**Comment by shuvalov-anton** [comment]
'Cause you can setup an exclude mask like `\/node_modules\/(?!.*es6)` to process just `*.es6` files from your `node_modules/` that are excluded by default.

**Comment by shuvalov-anton** [comment]
You'll get slow build if you process all your `node_modules` by es6-transpiller.

**Comment by shuvalov-anton** [comment]
Can I close the issue? Any objections or suggestions?

**Comment by globexdesigns** [comment]
This is still the only library I've seen that uses a .es6 extension. It seems like it would cause more issues than its worth, but it's your call.

From my point of view, adding a webpack rule to transpile a specific library (ie. /node_modules/es6-class-mixin/) is no different than having to add a rule to transpile .es6 files (ie. /node_modules/*.es6).

Closing.

**Comment by michaelBenin** [comment]
Also agree with globex here on the es6 extension, especially now that it's es2015.
