### ISSUE TITLE
Take inherited properites into account

### ISSUE THREAD

**Issue by moll** [rambler-digital-solutions/es6-class-mixin#2]
Hey,

Because the parent's inherited properties are taken into account, I'd say so should mixin's. Otherwise it's inconsistent. ;-)

**Comment by shuvalov-anton** [comment]
Hi! Can you provide simple test case?

**Comment by moll** [comment]
Sure. I'll type it out here straight without testing. :innocent: 

```js
var Draggable = {drag: function() {}}

var MyDraggable = Object.create(Draggable)
MyDraggable.dragAndLog = function() { this.drag(); console.log("Dragged") }

class DraggableItem extends mixin(ListItem, MyDraggable) {}
new DraggableItem().drag()
new DraggableItem().dragAndLog()
```
That's a simple example. Imagine `Draggable` is more complex and so on.

**Comment by moll** [comment]
In other words, you need only replace the `Object.keys` with a `for in` loop to make it consistent. The avoidance of inherited properties is FUD from ES3 days. ;-)

**Comment by shuvalov-anton** [comment]
@moll thx! I'll hack it at this weekends. Or you can make pull request if you want, just make me know :D
