### ISSUE TITLE
Remove debug from dependencies?

### ISSUE THREAD

**Issue by michaelBenin** [rambler-digital-solutions/es6-class-mixin#5]
Is debug included in the actual build?

If it is can we remove it? I'm developing something targeting mobile.

https://github.com/visionmedia/debug/blob/master/dist/debug.js

**Comment by shuvalov-anton** [comment]
I think, yes. Please make pull request and I will merge and release it.

**Comment by michaelBenin** [comment]
https://github.com/rambler-digital-solutions/es6-class-mixin/pull/6

**Comment by michaelBenin** [comment]
Merged.
